### ISSUE TITLE
MythicCasual

### ISSUE THREAD

**Issue by dota2iaeblan** [MezaMC/MezaBook#13]
discord.gg/mythiccasual - дискорд, айпи - 138.201.122.104:24093 версия 1.19.4 - 1.20.1
Игроки должны находить артефакты, также проходить испытания в особняке, не давно они нашли артефакт и кинули в варонку и там уже началось, кхм я хз чо мне говорить про сервер, ну типо на платном хосте, ночью +- 15 онлайна, утром бывало 10, а днём стабильно 5-6 онлайна. про ник забейте это акк брата ^D, мне потом он пизды даст .-.

**Comment by envizar** [comment]
Описание очень сумбурное и длинное. Прошу сформулировать его покороче.
Про онлайн сильно сомневаюсь (почему ночью 15 онлайна, а днём 5), но минимальным требованиям сервер удовлетворяет

**Comment by dota2iaeblan** [comment]
> Описание очень сумбурное и длинное. Прошу сформулировать его покороче. Про онлайн сильно сомневаюсь (почему ночью 15 онлайна, а днём 5), но минимальным требованиям сервер удовлетворяет

Я не знаю почему онлайн так действует, не которые игроки могут подтвердить и админы, описание могу скинуть с ии, мне лень писать :d

**Comment by dota2iaeblan** [comment]
> Описание очень сумбурное и длинное. Прошу сформулировать его покороче. Про онлайн сильно сомневаюсь (почему ночью 15 онлайна, а днём 5), но минимальным требованиям сервер удовлетворяет

И ещё про онлайн говорю примерно, то что вчера такой онлайн был.

**Comment by envizar** [comment]
Добавил

**Comment by dota2iaeblan** [comment]
> Добавил

Спасибо
