### ISSUE TITLE
WarpedRedux

### ISSUE THREAD

**Issue by ZarsQv** [MezaMC/MezaBook#14]
WarpedRedux - возвращение легендарного мистического сервера. Новая история, новые возможности 
IP - WarpedRedux.online
Цвета названия в описании - в лс (честно, палить не хочу)

**Comment by envizar** [comment]
Добавлю, как дома будешь
Палить не хочешь? У мезабука весь исходный код открыт, спалишь в любом случае

**Comment by ZarsQv** [comment]
> Добавлю, как дома буду Палить не хочешь? У мезабука весь исходный код открыт, спалишь в любом случае

окей.

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/62c8d2b011b7d7ccd3bc5108bcb5c17145d7b546
