### ISSUE TITLE
nightmarish.space

### ISSUE THREAD

**Issue by ikuna20** [MezaMC/MezaBook#17]
Описание - "Всегда проверяйте, не в кошмаре ли вы.."
Айпи - nightmarish.space
Дискорд - https://dsc.gg/nightmarish
Примечание - сервер если что на раннем доступе, и там могут играть определенные игроки, а так, с ранним доступом онлайн от двух до пяти или шести

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/21be21b0b34538a18e7c16d02764fafc7761d3d3
