### ISSUE TITLE
MisticSimple

### ISSUE THREAD

**Issue by AnZyyX** [MezaMC/MezaBook#20]
Discord: https://discord.gg/zxYemfak
ip: MisticSimple.aternos.me:28873
Это потерянный сервер где был один страшный инцидент при котором в мире случилось огромная трагедия.
После этого игроки сервера пропали. И я вам даю должность найти этого мифа. 
Не утеряйте шанс найти мистику!

**Comment by envizar** [comment]
![изображение](https://github.com/MezaMC/MezaBook/assets/87126318/faef274c-49f6-4285-856b-ba59799cf2c0)
