### ISSUE TITLE
Emptycult, mystic server.

### ISSUE THREAD

**Issue by CJ5Official** [MezaMC/MezaBook#21]
Discord server: https://discord.com/invite/FHdbYfHB7b
Server IP: Emptycult.aternos.me
Version indeed: 1.20.4
This server hosted in aternos.

**Comment by nowenc** [comment]
![image](https://github.com/MezaMC/MezaBook/assets/103275178/7ce97d38-2c04-42ab-9355-154d50b123c1)
![image](https://github.com/MezaMC/MezaBook/assets/103275178/6457d1bc-2bbc-4b08-96f7-3c988b940caf)

**Comment by skilixOff** [comment]
чувак, он иностранец. Как он поймет?

**Comment by nowenc** [comment]
Пусть переводчиком воспользуется, для этого интернет вроде и существует.

**Comment by ikuna20** [comment]
This monitoring is not supported by Aternos Hosting, buy any other hosting 24/7 and then send a request.

**Comment by ikuna20** [comment]
Как смешно

**Comment by CJ5Official** [comment]
> This monitoring is not supported by Aternos Hosting, buy any other hosting 24/7 and then send a request
I doesn't has money, fuck you then.

**Comment by CJ5Official** [comment]
Why you asking me to buy 24/7 if i doesn't has money.

**Comment by ikuna20** [comment]
Иди нахуй шалава

**Comment by nowenc** [comment]
> Иди нахуй шалава

Как не удивительно, что СНГ комьюнити мистических серверов посылает просто "нахуй" и оскорбляя при этом.

**Comment by nowenc** [comment]
> Why you asking me to buy 24/7 if i doesn't has money.

Bro, don’t try to integrate with this site, the community here has been toxic lately.

**Comment by ikuna20** [comment]
Защитник нашёлся

**Comment by nowenc** [comment]
> Защитник нашёлся

Я видел твои высказывания на некоторых серверах, ты совсем смешной персонаж.

**Comment by ikuna20** [comment]
Капец, ты прям сталкер

**Comment by envizar** [comment]
насрали прям на гитхабе, позор

**Comment by envizar** [comment]
@CJ5Official We accept only servers on paid hosts because all mystic servers on aternos I've seen so far have very low quality.
