### ISSUE TITLE
Orbitium

### ISSUE THREAD

**Issue by orbitium-online** [MezaMC/MezaBook#24]
IP: orbitium.online
Discord: https://discord.gg/orbitium
Orbitium - Начало новой истории..

**Comment by ikuna20** [comment]
Через месяц или две закроется по причине "типо краш" прям как дарт в старые года.

**Comment by orbitium-online** [comment]
> Через месяц или две закроется по причине "типо краш" прям как дарт в старые года.

Типичный икуна, ыыы Orbitium  закроется через месяц или два. Мы ещё посмотрим чей проект закроется.

**Comment by ikuna20** [comment]
Ну хз хз, Твой прошлый проект наверное сам крашнулся, а почему ты сразу переходишь на найтмариш я рил хз, Разница лишь в том что я не делаю самокраши для поднятия актива, а если хочу, то нормально закрываю проект без всяких цирков по типу "аааа ребята меня взломали через Программу танчики 2009 которую скачал мой дед"

**Comment by orbitium-online** [comment]
> Ну хз хз, Твой прошлый проект наверное сам крашнулся, а почему ты сразу переходишь на найтмариш я рил хз, Разница лишь в том что я не делаю самокраши для поднятия актива, а если хочу, то нормально закрываю проект без всяких цирков по типу "аааа ребята меня взломали через Программу танчики 2009 которую скачал мой дед"

И как Orbitium и другие мои проекты связаны? По твоей логике я создаю проект, а через день его крашаю и создаю новый.

**Comment by ikuna20** [comment]
Причина Закрытия орбитиума - нехватка актива, а там собственно ты создал новый аккаунт на котором был новый сервер, оправдывая тем что "он никак не связан с орбитиумом и со мной", слава богу что ты не делаешь самокраши каждый день, Минимум месяц или два, как я высшее упомянул - нехватка актива и желание Хорошо так похайпить.
В 23 году ты ваще каждую недели новый проект создавал и говорил что старый удалился сам, Оправдывая тем что ты там чето скачал и тебя взломали.

**Comment by ikuna20** [comment]
Ты ещё скажи что ты не раф и орбитиум не твой проект, Будет ещё одно оправдание.

**Comment by ikuna20** [comment]
И да, пошли лучше в лс, это лучше чем разбираться на гитхабе🙋

**Comment by orbitium-online** [comment]
> Ты ещё скажи что ты не раф и орбитиум не твой проект, Будет ещё одно оправдание.

Икуна, тебе совсем плохо стало? Где я говорил что Orbitium владеет другой человек? Было такое что я писал с другого аккаунта в новости, но это был сюжет. А сейчас Orbitium никак не связан по сюжету со старым сервером.

**Comment by ikuna20** [comment]
Если ты прям так хочешь

**Comment by orbitium-online** [comment]
> И да, пошли лучше в лс, это лучше чем разбираться на гитхабе🙋

пошли, я есть в группе меза (orbitium).

**Comment by skilixOff** [comment]
> И да, пошли лучше в лс, это лучше чем разбираться на гитхабе🙋

тут оставайтесь, я читать хочу

**Comment by orbitium-online** [comment]
> тут оставайтесь, я читать хочу

могу сделать группу с тобой и икуной
