### ISSUE TITLE
Demonstrate

### ISSUE THREAD

**Issue by Demonstratehaos** [MezaMC/MezaBook#25]
Вы чувствуете? Они наблюдают за тобой!
Вот дискорд: https://discord.com/invite/mJc8DhwaQF
Айпи:178.63.10.85:25572
Версия: 1.19.4, выше поддерживается

**Comment by Plusheshka** [comment]
а можно телеграмм канал добавить? https://t.me/+0tYnsyFrrMc0Njhi

**Comment by aBobby5415** [comment]
> а можно телеграмм канал добавить? https://t.me/+0tYnsyFrrMc0Njhi

ещё не добавили возможность указать телеграм в мониторинге, жди

**Comment by Plusheshka** [comment]
Окей

**Comment by Plusheshka** [comment]
У нас айпи поменялся ещё - 212.80.7.207:20077

**Comment by Plusheshka** [comment]
Прошу пожалуйста убрать это описание.

**Comment by envizar** [comment]
> Прошу пожалуйста убрать это описание. Если конечно можно пустым оставить.

Можно
