### ISSUE TITLE
New Alliance

### ISSUE THREAD

**Issue by Tapocheck103** [MezaMC/MezaBook#27]
Minecraft server-New Alliance
IP MINECRAFT-d30.gamely.pro:20133
DISCORD-https://discord.com/invite/JNKCzGYQ3U

После продолжительной [ВЫРЕЗАНО], завод превратился в руины, остатки прошлого по сей день есть в этом мире, ведь он никуда не исчез. Люди должны разгадать что произошло и кто все эти [ВЫРЕЗАНО]. Приветствуем вас на новом сервере New Alliance! Этот мир полон загадок которые вы должны узнать!

**Comment by Tapocheck103** [comment]
> Minecraft server-New Alliance IP MINECRAFT-d30.gamely.pro DISCORD-https://discord.com/invite/JNKCzGYQ3U
> 
> После продолжительной [ВЫРЕЗАНО], завод превратился в руины, остатки прошлого по сей день есть в этом мире, ведь он никуда не исчез. Люди должны разгадать что произошло и кто все эти [ВЫРЕЗАНО]. Приветствуем вас на новом сервере New Alliance! Этот мир полон загадок которые вы должны узнать!

**Comment by skilixOff** [comment]
удаляй при мне

**Comment by Tapocheck103** [comment]
Не обязан

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/207e4235d9406ac9a2966a29cbde05fea76e80df
