### ISSUE TITLE
Dishade

### ISSUE THREAD

**Issue by whatymru** [MezaMC/MezaBook#29]
### Адрес сервера

138.201.142.120:25696

### Небольшое описание сервера

Интересный мистический сервер.

### Прочие пожелания

Цвет для название можно #C1A685 

### Discord сервер

https://discord.com/invite/nWt9K3Ztts

### YouTube канал

https://www.youtube.com/@Dishade_Server

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by skilixOff** [comment]
щедрое описание

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/cabea78bce18e62a6c65b20de5671a369310ca24
