### ISSUE TITLE
About

### ISSUE THREAD

**Issue by DARKMAKSS** [MezaMC/MezaBook#31]
_`Uɳԃʋιƙ ԃҽ ԃყʂƚɾα . .`_

`Developer noticed the strange activity with armor stands, and he heard the terrifying roar of some creature.`

`As a group of developers, we are currently trying to figure out what it is.`
.
.
.
![Screenshot](https://github.com/user-attachments/assets/f7307826-5f61-41b3-adbf-862885b004dc)

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/4fcf7a08aca83a5e07b3c9bb24b1894015add048
