### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Wizer123cat** [MezaMC/MezaBook#32]
### Адрес сервера

wizer123cat.666

### Небольшое описание сервера

...

### Прочие пожелания

...

### Discord сервер

https://discord.gg/345

### YouTube канал

https://www.youtube.com/@user-kv3gc2xp1o

### Условия

- [ ] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by Wizer123cat** [comment]
...

**Comment by skilixOff** [comment]
> ...

ты рекламиться пытаешься или рил ссылка дс баганулась?

**Comment by envizar** [comment]
опять насрал
