### ISSUE TITLE
OminousVoid

### ISSUE THREAD

**Issue by makc573** [MezaMC/MezaBook#33]
### Адрес сервера

OminousVoid.su

### Небольшое описание сервера

проклятый сервер там проподают игрок

### YouTube канал

https://www.youtube.com/watch?v=wNRfmEqUbvM

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
Хватит срать сюда, пишите нормально
