### ISSUE TITLE
 Xmine

### ISSUE THREAD

**Issue by makc573** [MezaMC/MezaBook#35]
### Адрес сервера

XMine.su 

### Небольшое описание сервера

грифиский сервер но с мистика есть сервер ютубера роменский

### Ссылка на сайт

https://xmine.store/

### YouTube канал

https://www.youtube.com/watch?v=2UGz83WD8Ho

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
https://github.com/user-attachments/assets/97f90a9a-4019-4339-918c-53cedd011a31
