### ISSUE TITLE
Изменение описания сервера NewAlliance на mezabook

### ISSUE THREAD

**Issue by New-AllianceMC** [MezaMC/MezaBook#36]
### Адрес сервера

65.109.58.46:20133

### Небольшое описание сервера

&4they are watching

### Discord сервер

https://discord.gg/RVRFnCbb6k

### YouTube канал

https://youbube.com/

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/dc2ab67610d8dc1d9b29c57dc33582adc832efa4
