### ISSUE TITLE
aternos

### ISSUE THREAD

**Issue by igrok098** [MezaMC/MezaBook#38]
### Адрес сервера

bebrafujZj2x.aternos.me:44566

### Небольшое описание сервера

я сам заходил и видел мистику открывались сундуки непонятные звуки в начале было а потом вылетало у меня

### Прочие пожелания

тут надо было ждать 10 дней а на 10 дне начиналось мистика

### Discord сервер

нету

### Ссылка на сайт

нету 

### YouTube канал

у сервера нету ни сайта ни дискорда

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
aternos это не платный хостинг.
