### ISSUE TITLE
The mistical server

### ISSUE THREAD

**Issue by hlochik709** [MezaMC/MezaBook#39]
### Адрес сервера

hlochik709.aternos.me:11335

### Небольшое описание сервера

сервер с мистикой и .

### Прочие пожелания

dfnzdtjsvresdnumfdszefsdbduoVOPCJSUABHdqko

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by aBobby5415** [comment]
Зачем вы срёте?
Атернос далеко не платный хостинг как минимум

**Comment by envizar** [comment]
Опять спермосом насрали
