### ISSUE TITLE
ПОМОГИ СДЕЛАТЬ ХОРОШИЙ СЕРВЕР С МИСТИКОЙ!!!

### ISSUE THREAD

**Issue by hlochik709** [MezaMC/MezaBook#40]
### Адрес сервера

hlochik709.aternos.me:11335

### Небольшое описание сервера

это будущий мистический сервер. Просьба: любого игрока хочу попросить зайти на сервер и объяснить как сделать его интересным, да это пока что не мистик сервер, просто кто нибудь зайдите и помогите превратить этот мир - в место где игроки хорошо проведут время...

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
откроешь ещё один issue с атернос сервером - полетишь в блок
aternos - бесплатный хостинг. в мониторинге только сервера, что стоят на платном хостинге, чтобы гарантировать хоть какое-то минмальное качество и аптайм

**Comment by hlochik709** [comment]
Как сделать сервер если там галочку платный хостинг обязательно ставить

чт, 17 окт. 2024 г., 20:40 envizar ***@***.***>:

**Comment by hlochik709** [comment]
???

чт, 17 окт. 2024 г., 20:41 BeezY ***@***.***>:

**Comment by envizar** [comment]
> Как сделать сервер если там галочку платный хостинг обязательно ставить

Так зачем ты её поставил? Если не на платном хостинге - нельзя вообще добавлять

**Comment by hlochik709** [comment]
Там если ее не поставить я не смогу сервер в сеть выложить. А что можно как
то по другому серв сделать?

чт, 17 окт. 2024 г., 20:44 envizar ***@***.***>:

**Comment by envizar** [comment]
> Там если ее не поставить я не смогу сервер в сеть выложить. А что можно как
> то по другому серв сделать?

у мониторинга есть критерии, под которые твой сервер не подходит
поэтому на мониторинге твой сервер находиться не может

если вопрос "можно ли как-то иначе сервер сделать" относится к теме хостингов, то да, существуют платные хостинги. например, bisquit host или [play2go](https://p2g.meza.one)

**Comment by hlochik709** [comment]
То есть за создание серверов нужно платить? В общем я чайник в этом деле, я
даже не знал чо такое платный хостинг. Ладно сегодня удалю серв.

чт, 17 окт. 2024 г., 20:51 envizar ***@***.***>:
