### ISSUE TITLE
пробный мистический сервер...

### ISSUE THREAD

**Issue by hlochik709** [MezaMC/MezaBook#41]
### Адрес сервера

hlochik709.aternos.me:11335

### Небольшое описание сервера

пробный сервер с мистикой, (админы на сервере тоже будут играть, по этому не обращайте внимания на какие то изменения. СЕРВЕР НА БЕСПЛАТНОМ ХОСТИНГЕ!!! удачной игры)

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
я тебе писал: "ещё раз отправишь атернос сервер - получишь блокировку в репозитории"
если не хватает ума понять смысл написанного - увы, отлетаешь в блок
