### ISSUE TITLE
Crimsonium

### ISSUE THREAD

**Issue by ArchmageMito** [MezaMC/MezaBook#42]
### Адрес сервера

212.80.7.203:20052

### Небольшое описание сервера

Мистический сервер со своими интересными мифами и сюжетом. Погрузитесь в мир мистики!

### Discord сервер

https://discord.gg/P4nZnX2pG7

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by ArchmageMito** [comment]
> ### Адрес сервера
> 212.80.7.203:20052
> 
> ### Небольшое описание сервера
> Мистический сервер со своими интересными мифами и сюжетом. Погрузитесь в мир мистики!
> 
> ### Прочие пожелания
> _No response_
> 
> ### Discord сервер
> https://discord.gg/P4nZnX2pG7
> 
> ### Ссылка на сайт
> _No response_
> 
> ### YouTube канал
> _No response_
> 
> ### Условия
> * [x]  Сервер расположен на платном хостинге
> * [x]  Сервер соответствует мистической тематике

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/0100a0d6b20c408ca7ded7987591a54753d594ec

**Comment by envizar** [comment]
![изображение](https://github.com/user-attachments/assets/658629ee-386b-4836-99f7-4a4fd184bd52)
https://github.com/MezaMC/MezaBook/commit/36867c6f45f9d0ae6c02025388f3bdd177ed939f

**Comment by ArchmageMito** [comment]
<gradient:#ff347e:#9f8bff>Crimsonium</gradient>

**Comment by envizar** [comment]
> gradient:#ff347e:#9f8bffCrimsonium

https://github.com/MezaMC/MezaBook/commit/d1e294fb90152302fac68f4641643a39a5fa80d0
