### ISSUE TITLE
HorrorCraft

### ISSUE THREAD

**Issue by makc573** [MezaMC/MezaBook#43]
### Адрес сервера

bfghii.falixsrv.me

### Небольшое описание сервера

хоррор сервер который сможет вас напугать и есть несколько мифов и скримеры версия 0.0

### Прочие пожелания

обводка чтобы была страшная и искажёная

### Discord сервер

https://discord.gg/F6aEqRbh

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
Сервер стоит на платном тарифе? Сомневаюсь

**Comment by makc573** [comment]
он стоит на https://client.falixnodes.net

**Comment by envizar** [comment]
> он стоит на https://client.falixnodes.net

Тариф-то платный? У FalixNodes есть бесплатный тариф, судя по всему сервер стоит как раз на нём

**Comment by makc573** [comment]
да

**Comment by envizar** [comment]
нельзя добавить на мониторинг сервер, который стоит на бесплатном тарифе
