### ISSUE TITLE
Добавление ссылок.

### ISSUE THREAD

**Issue by SurvivalHome** [MezaMC/MezaBook#44]
Здраствуйте! Прошу добавить к SurvivalHome такие ссылки как

Boosty: https://boosty.to/survivalhome
Telegram: https://t.me/survivalhome
YouTube: https://www.youtube.com/@SurvivalHomeserver

заранее спасибо!

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/70a82d1a3d3af480bca74db22de4737685332196
