### ISSUE TITLE
Ckil123Lloo

### ISSUE THREAD

**Issue by Ckil123Lloo** [MezaMC/MezaBook#45]
### Адрес сервера

ckil123Lloo.fun

### Небольшое описание сервера

Приветствую вас на сервер просто выживание

### Прочие пожелания

Не гриферить 

### Telegram канал

https://t.me/+ys7JcLFr1ydlMDc6

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by Ckil123Lloo** [comment]
Приветствую на сервер удачи выживаниях

**Comment by skilixOff** [comment]
ты че ебанутый
