### ISSUE TITLE
ɧąųŋɬɛɖ

### ISSUE THREAD

**Issue by whattalite** [MezaMC/MezaBook#47]
### Адрес сервера

212.80.7.212:20006

### Небольшое описание сервера

&7Туман поглощает последние лучи света

### Прочие пожелания

Название сервера градиент: gradient:#282828:#A5A5A5ɧąųŋɬɛɖ

### Discord сервер

https://discord.gg/kRnSZ57e4u

### Telegram канал

https://t.me/hauntedcraft

### YouTube канал

https://www.youtube.com/@HauntedCraftYT

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
https://github.com/MezaMC/MezaBook/commit/07784c16a87226397c577715a3f75b4135dfa57a
