### ISSUE TITLE
REMOVER WORLD

### ISSUE THREAD

**Issue by makc573** [MezaMC/MezaBook#51]
### Адрес сервера

скоро

### Небольшое описание сервера

скоро сервер появился 2 дня назат

### Discord сервер

https://discord.gg/yrRkqTUm

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
вот когда сервер будет готов - тогда и приходите
