### ISSUE TITLE
Netherbrine 

### ISSUE THREAD

**Issue by 1MMMMMMMMM** [MezaMC/MezaBook#54]
### Адрес сервера

CRystaryCrafu.aternos.me:33260

### Небольшое описание сервера

Всегда смотр назад

### Discord сервер

https://discord.gg/wDE4KbqS

### Telegram канал

t.me/cyetoc

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by 1MMMMMMMMM** [comment]
👍

**Comment by envizar** [comment]
атернос это не платный хостинг

![изображение](https://private-user-images.githubusercontent.com/87126318/389088811-6442f566-f057-40fd-9c14-d84a8ff9e8ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2Mzk4MDYsIm5iZiI6MTczMjYzOTUwNiwicGF0aCI6Ii84NzEyNjMxOC8zODkwODg4MTEtNjQ0MmY1NjYtZjA1Ny00MGZkLTljMTQtZDg0YThmZjllOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE2NDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjY2E2NmVlOGU2YmRkYmRmMzJmN2E1YzRkYjU0NjI1MDdlZjE4Mzc2NzU2Njc2ZTczZTc3ZDViZGI0OTViNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ouiEb3Ff3AxMHdPN5WIVI4RnOkEdhKw0edkLuLPEW1U)
