### ISSUE TITLE
dataworld0

### ISSUE THREAD

**Issue by mistika666** [MezaMC/MezaBook#59]
### Адрес сервера

dataworld0.aternos.me:14293

### Небольшое описание сервера

остерегайтесь data0

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
🐒

**Comment by mistika666** [comment]
сервер будет онлайн в 17:30-18:30

**Comment by skilixOff** [comment]
лолфнак обеднел и ушел на атернос
