### ISSUE TITLE
OliWorld 

### ISSUE THREAD

**Issue by Reppl-dev** [MezaMC/MezaBook#61]
### Адрес сервера

oliworld-wQCy.aternos.me:30445

### Небольшое описание сервера

Мистический сервер, вдохновленный Siimpalone . Окунитесь в этот удивительный мир мистики.И узнайте тайну мира.Советую заходить в дискорд сервер , потому сервер на антерносе.Чтобы говорить когда включён !

### Прочие пожелания

**
![Uploading Screenshot_20241221-002720.png…]()
**

### Discord сервер

https://discord.gg/VPp6QwF9

### Условия

- [X] Сервер расположен на платном хостинге
- [X] Сервер соответствует мистической тематике

**Comment by envizar** [comment]
никакого атерноса
