### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by DARKMAKSS** [MezaMC/MezaBook#7]
# UnknownDead
Tԋҽ ɱσʂƚ ƚҽɾɾιႦʅҽ αɳԃ 
ԃҽɱσɳιƈ ʂҽɾʋҽɾ.

## • Information • 
```
+ IP: 198.251.89.194:20096
+ Version: 1.20.1 
+ Licens: Inte nödvändig.
```

**Comment by envizar** [comment]
https://book.meza.one/community/servers/UnknownDead
